version: "3.9"

services:
  frontend:
    build: ./
    volumes:
      - ./public:/public
      - ./src:/src
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run start-dev
